id: P000689
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159525
  title: ༢༠༡༡ལོའི་ལྷུག་རྩོམ།
  author: ''
  volumes:
    249e9195992b44a19cccd50fae2de7d2:
      image_group_id: I2PD18969
      title: ''
      volume_number: 1
      total_pages: 292
